on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JBR
        uses: actions/setup-java@v4
        with:
          distribution: "jetbrains"
          java-package: "jdk"
          java-version: "21"
          check-latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Gradle (with cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        shell: bash
        run: |
          sdkmanager --install "platforms;android-36" "build-tools;36.1.0"

      - name: Build Debug APK
        shell: bash
        run: |
          ./gradlew :app:assembleDebug

      - name: Stop Gradle Daemons
        shell: bash
        run: |
          ./gradlew -stop

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/outputs/apk/debug/*.apk
          name: app-android
